<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFncXWFd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFncXWFd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFncXWFd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFncXWFd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFncXWFd\App_KernelDevDebugContainer([
    'container.build_hash' => 'FncXWFd',
    'container.build_id' => 'cd2d1287',
    'container.build_time' => 1685601748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFncXWFd');
